function gui
guessPath = [];
figure('name','MastermindSolver',...
    'numbertitle','off',...
    'menubar','none',...
    'position',[440,200,400,400]);
uicontrol('style','pushbutton',...
    'String','Solve',...
    'Position',[175,250,50,50],...
    'Callback',@Solve);
uicontrol('style','text',...
    'string','Guess Attempts',...
    'position',[260,180,110,50],...
    'fontsize',10);
uicontrol('style','text',...
    'string','Guess Path',...
    'position',[145,180,110,50],...
    'fontsize',10);
GUESS=uicontrol('style','text',...
    'string','',...
    'position',[260,155,110,50],...
    'fontsize',10,...
    'Callback',@solve);
A=uicontrol('style','text',...
    'string','',...
    'position',[175,155,50,50],...
    'fontsize',10);
B=uicontrol('style','text',...
    'string','',...
    'position',[175,140,50,50],...
    'fontsize',10);
C=uicontrol('style','text',...
    'string','',...
    'position',[175,125,50,50],...
    'fontsize',10);
D=uicontrol('style','text',...
    'string','',...
    'position',[175,110,50,50],...
    'fontsize',10);
E=uicontrol('style','text',...
    'string','',...
    'position',[175,95,50,50],...
    'fontsize',10);
F=uicontrol('style','text',...
    'string','',...
    'position',[175,80,50,50],...
    'fontsize',10);
G=uicontrol('style','text',...
    'string','',...
    'position',[175,65,50,50],...
    'fontsize',10);
H=uicontrol('style','text',...
    'string','',...
    'position',[175,50,50,50],...
    'fontsize',10);
uicontrol('style','text',...
    'string','Solution',...
    'position',[89,317,50,50],'fontsize',10);
uicontrol('style','text',...
    'string','Guess',...
    'position',[89,290,50,50],'fontsize',10);
solution=uicontrol('Style','edit',...
          'String','',...
          'HorizontalAlignment','center',...
          'Enable','on',...
          'Units','pixel',...
          'Position',[145,350,115,20]);
Guess=uicontrol('Style','edit',...
          'String','',...
          'HorizontalAlignment','center',...
          'Enable','on',...
          'Units','pixel',...
          'Position',[145,320,115,20]);
      
pop=uicontrol('Style','popupmenu',...
          'String',{'Random','Strategy Two','Strategy Three','Knuth'},...
          'Enable','on',...
          'Units','pixel',...
          'Position',[30,180,110,50],...
          'Callback',@assign);
% Display popupmenu selection                
function assign(~,~)
    val = pop.Value;
    str = pop.String;
    disp(['Selection: ' str{val}]);       
end
% Solve      
function Solve(~,~)
    path = [A B C D E F G H];           % Eight empty slots
    set(path,'string','')
    Solution = get(solution,'string');
    guess = get(Guess,'string');
    % Set choice of solving 
    val = pop.Value;
    str = pop.String;
    switch str{val}
        case 'Random'
            choice = 1;
        case 'Strategy Two'
            choice = 2;
        case 'Strategy Three'
            choice = 3;
        case 'Knuth'
            choice = 4;
        otherwise
            choice = 1;
    end
    % Solve
    guessPath = MastermindSolver(Solution,guess,choice);
    % update gui
    for ii=1:size(guessPath,2)
        set(path(ii),'string',guessPath(1,ii));
    end
    set(GUESS,'string',size(guessPath,2))
end
end